# Generated by Django 4.1.5 on 2023-01-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_trading_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='stocks',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('stockId', models.ManyToManyField(to='simple_trading_system.stock')),
                ('userId', models.ManyToManyField(to='simple_trading_system.trader')),
            ],
        ),
    ]
