# Generated by Django 4.1.5 on 2023-01-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_trading_system', '0002_remove_trader_quantity_remove_trader_stocks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trader',
            old_name='LastName',
            new_name='lastName',
        ),
    ]
